// @ts-nocheck -- skip type checking
import * as docs_10 from "../content/docs/components/tape-deck.mdx?collection=docs"
import * as docs_9 from "../content/docs/components/simple-search.mdx?collection=docs"
import * as docs_8 from "../content/docs/components/prompt-input.mdx?collection=docs"
import * as docs_7 from "../content/docs/components/particle-dissolve.mdx?collection=docs"
import * as docs_6 from "../content/docs/components/organic-growth.mdx?collection=docs"
import * as docs_5 from "../content/docs/components/model-selector.mdx?collection=docs"
import * as docs_4 from "../content/docs/components/goo-search.mdx?collection=docs"
import * as docs_3 from "../content/docs/components/folder.mdx?collection=docs"
import * as docs_2 from "../content/docs/components/file-attachment.mdx?collection=docs"
import * as docs_1 from "../content/docs/components/click-spark.mdx?collection=docs"
import * as docs_0 from "../content/docs/components/button.mdx?collection=docs"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"components/button.mdx","fullPath":"content\\docs\\components\\button.mdx"}, data: docs_0 }, { info: {"path":"components/click-spark.mdx","fullPath":"content\\docs\\components\\click-spark.mdx"}, data: docs_1 }, { info: {"path":"components/file-attachment.mdx","fullPath":"content\\docs\\components\\file-attachment.mdx"}, data: docs_2 }, { info: {"path":"components/folder.mdx","fullPath":"content\\docs\\components\\folder.mdx"}, data: docs_3 }, { info: {"path":"components/goo-search.mdx","fullPath":"content\\docs\\components\\goo-search.mdx"}, data: docs_4 }, { info: {"path":"components/model-selector.mdx","fullPath":"content\\docs\\components\\model-selector.mdx"}, data: docs_5 }, { info: {"path":"components/organic-growth.mdx","fullPath":"content\\docs\\components\\organic-growth.mdx"}, data: docs_6 }, { info: {"path":"components/particle-dissolve.mdx","fullPath":"content\\docs\\components\\particle-dissolve.mdx"}, data: docs_7 }, { info: {"path":"components/prompt-input.mdx","fullPath":"content\\docs\\components\\prompt-input.mdx"}, data: docs_8 }, { info: {"path":"components/simple-search.mdx","fullPath":"content\\docs\\components\\simple-search.mdx"}, data: docs_9 }, { info: {"path":"components/tape-deck.mdx","fullPath":"content\\docs\\components\\tape-deck.mdx"}, data: docs_10 }], [])